### ISSUE TITLE
`ezspawn` and `@jsdevtools/ez-spawn`

### ISSUE THREAD

**Issue by benmccann** [es-tooling/module-replacements#141]
can be migrated to `tinyexec`

**Comment by benmccann** [comment]
The vitest folks are interested in migrating to `tinyexec`, but first they want to migrate https://github.com/antfu/install-pkg to it, which they also use. Looking at that package, it is setting an option `stdio: options.silent ? 'ignore' : 'inherit',` that `tinyexec` doesn't have. @43081j do you have any guidance on migrating that option? Should I file an issue requesting it in `tinyexec`?

**Comment by 43081j** [comment]
you can access the underlying node options via `nodeOptions`:

```ts
await x('ls', ['-l'], {
  nodeOptions: {
    stdio: options.silent ? 'ignore' : 'inherit'
  }
});
```

something like this should work

**Comment by ehmicky** [comment]
This should really come with some caveats. Execa comes with many useful features for anyone [executing commands](https://github.com/sindresorhus/execa/#features). Some are arguably edge cases (transforming input/output, exchanging messages, etc.) but some are pretty important:
  - Full [Windows support](https://github.com/sindresorhus/execa/blob/main/docs/windows.md). Node.js core `node:child_process` has several issues which have never been fixed despite having been reported for 5-10 years. Running cross-platform code is quite important.
  - An approach which avoids any risk of [command injection](https://github.com/sindresorhus/execa/blob/main/docs/shell.md), for anyone who cares about security.
  - Great [debugging](https://github.com/sindresorhus/execa/blob/main/docs/debugging.md) and [error information](https://github.com/sindresorhus/execa/?tab=readme-ov-file#debugging). Commands run in a separate process which makes them harder to debug. It's really helpful to use a tool which gives you some additional information when you're wondering why a specific command is not behaving in the way you'd expect it to.

**Comment by sindresorhus** [comment]
As an anecdote, my [Got](https://github.com/sindresorhus/got) package started out being 1 kB initially ([now it's 237 kB](https://packagephobia.com/result?p=got) - network is hard), but through the years it had actual usage in production and had to handle a lot of different important use-cases and cover a lot of edge-cases, and that's where the size comes from. It's easy to start fresh with a tiny library, but it's a big fallacy. Tiny libraries are ones that have not had enough use in production.

**Comment by 43081j** [comment]
In cases where people need a full blown solution to these situations, it's perfectly valid for them to not use the alternatives we suggest

Many of the tiny libraries (such as those in tinylibs) Will not be growing much beyond what they are now. Battle testing them more may change the interface but the overall feature set is what it is. People can use fuller fat solutions if that isn't enough

Not all libraries continuously say yes to requests and end up 200x the size

**Comment by ehmicky** [comment]
> The usual list of benefits you mention, @ehmicky , have been considered. Places where we migrate, it is unlikely they are relevant.

I can see how easy debugging is not a priority for everyone, although it does solve some hour-long bug hunting headaches (in my own experience).

I can also see that cross-platform support might not be a concern for end-user applications. On the other hand, it _should_ be so for any Node module. 

When it comes to security, this is definitely something most developers would probably genuinely prioritize. They might not fully grasp the trade-off they are taking security-wise when switching away from those battle tested libraries. Execa has 5000 tests, is 8 years old, is used by 23 million repositories, but only has 2 open bugs (Windows-only, and might not be bugs actually). I'm sure it's got some additional bugs we are unaware of (because every software does) but it's a library developers can fully trust in a domain as security-sensitive as process spawning.

**Comment by 43081j** [comment]
I understood that 👍 I wasn't referring to just the feature set. Sorry if that wasn't clear

Options are good. Security will of course be important to tinyexec too, and working cross platform. 

In the end, it will come down to feature set (because both will work just as well across platforms and have the same level of security). Some projects will stay on execa because we need the features it has, many won't

**Comment by sindresorhus** [comment]
The issue is that when you ask maintainers to switch to a smaller package, you're not giving them the full picture (I've reviewed many of the pull requests made). Maintainers often focus on the size reduction and maybe the [misleading micro-benchmarks](https://sindresorhus.com/blog/micro-benchmark-fallacy), and think, "why not?" without fully considering the implications. They frequently overlook critical factors like package safety, longevity (many packages become unmaintained within a few years), npm deduplication, superior cross-platform support, better maintenance, subtle different behavior, missing functionality they might later need (things not caught by unit tests), not yet discovered bugs, and more.

**Comment by 43081j** [comment]
We have been taking it into account with alternatives we suggest. Everything you listed has been considered and often isn't a problem (e.g. better maintenance is certainly false, cross platform support will be equal over time if not already, etc etc) 

All benchmarks should be taken with a grain of salt and aren't the sole justification of packages we suggest

The community has worked well together around all of this

**Comment by bluwy** [comment]
I think there's truth in both sides and there's usecase where `execa` or `tinyexec` (or similar scoped libraries) make sense. 

As a library author, I often want to simply execute something (`npm install`, a node script, etc) and so I'd want to use a smaller library or even simply raw `child_process` if it can get the job done without the edge cases. I don't want users to pay for a larger library that I only use a small part of it.

As an application developer, or a library that heavily executes scripts, a larger library (like execa) would be a lot more appealing as it can handle the various commands safely. It's also more likely for me to use all the features execa has to offer.

When someone decides to use a smaller library or raw `child_process` (that may not handle all the edge cases), I think it's important to communicate the tradeoffs for sure, and not just size reduction, something `module-replacements` have also done for other packages. e.g. [qs](https://github.com/es-tooling/module-replacements/blob/main/docs/modules/qs.md), [moment](https://github.com/es-tooling/module-replacements/blob/main/docs/modules/momentjs.md).

It's also important to educate "when you don't need this library" or "when this simple implementation is enough", and let users judge the tradeoffs. We should strive for npm packages to only use the code and features they need as much as possible.

**Comment by benmccann** [comment]
@43081j could you re-open this? We need to add `exspawn` and `@jsdevtools/ez-spawn` still
