### ISSUE TITLE
Clarification / syncing position about polyfills

### ISSUE THREAD

**Issue by zloirock** [es-tooling/module-replacements#55]
I want to understand if we are doing the same job.

I'm working on engines compatibility, and [making polyfills and related tools](https://github.com/zloirock/core-js) is my main work.

I'm sure that polyfills should be used, and they can be useful even for features for old engines like IE11 if it's support required. Used polyfills can be easily replaced with native features when they bacame in target engines.

Polyfills should be maximally proper. However, users should not load polyfills that are not required for their target engines. Polyfills should not be bloated, they should not create a black hole in the `node_modules`, and they should not load something to the bundle that can be easily avoided - polyfills that I already added to this replacement list cause those problems.

The perfect polyfill should make a feature work, but it should not load any useless bytes to the bundle.

I'm working on polyfills architecture that should make it maximally optimizable. My polyfills can be injected and optimized by [Babel](https://babeljs.io/docs/babel-preset-env) and [SWC](https://swc.rs/docs/configuration/supported-browsers#corejs). My future vision for optimization is [here](https://github.com/zloirock/core-js/blob/master/docs/2023-02-14-so-whats-next.md#new-approaches-to-tooling-are-more-interesting).

Maybe, in the future, it makes sense to add to this project a rule that allow / disallow polyfills by a browserslist, like it's done [here](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-unnecessary-polyfills.md) - I maintain [some data sources](https://github.com/zloirock/core-js/tree/master/packages/core-js-compat) that allow it.

If our point of view coincides, I will continue to help the project.

**Comment by 43081j** [comment]
i think we're on the same page

polyfills are useful in many situations, especially when you need to support older browsers (happens a lot in corporate environments etc).

the manifest in this repo is the full list with node versions, etc. meanwhile, the `depend` lint plugin pulls these manifests in and filters them down based on your supported node versions.

maybe we could improve the lint plugin to have an option to use browserslist, too. 

e.g. i wouldn't expect core-js to end up in here because the polyfills are usually conditional and generally don't bloat bundles

**Comment by justinfagnani** [comment]
I think that a lot of polyfills _should_ end up in here, possibly with some kind of warning level. core-js for instance polyfills a lot of features that are available in most apps full target platform range, like Promise or Map. Even if conditionals, these shouldn't be usually depended on by libraries and can end up in bundles.

This difficulty with a project like core-js is that is polyfills so many things, some of which are necessary. It's not as easy to flag as say, setprototypeof, which is why I think it should be an optional warning.
