### ISSUE TITLE
replace tshy in module-replacements

### ISSUE THREAD

**Issue by kravetsone** [es-tooling/module-replacements#60]
Why u use it as package builder?

https://www.npmjs.com/package/tshy?activeTab=dependencies

![image](https://github.com/es-tooling/module-replacements/assets/57632712/1f5baed9-e3d4-422c-9623-8442e9049056)

It uses the packages that you say should be replaced...

I suggest use [pkgroll](https://www.npmjs.com/package/pkgroll?activeTab=readme) instead

**Comment by 43081j** [comment]
it does a fairly good job. the usual two choices for dual packages are tsup and tshy from what i've seen

tsup bundles the sources twice (which looks like what pkgroll does too), and tshy just builds via tsc twice

are you concerned about the dependency tree depth?

**Comment by AbhiPrasad** [comment]
`tshy` is great, I don't think it's a huge deal that the packages in the module-replacements list are being used because `rimraf` and similar is most just there to deal with `glob`: https://github.com/isaacs/sync-content/blob/acdce90c55eecc603945c935bffbbd3d377f1e2e/src/index.ts#L219-L220.

`tshy` also doesn't use rollup, which does help [keep it light](https://npmgraph.js.org/?q=tshy).

[`pkgroll`](https://www.npmjs.com/package/pkgroll) uses an [outdated version of glob](https://npmgraph.js.org/?q=pkgroll), which brings in the deprecated inflight, so feels like a worse option atm. It also brings in the whole rollup ecosystem, which is heavy in it's own right.

[`bunchee`](https://github.com/huozhi/bunchee) is another similar all-in-one dual emitting solution that I really like, but it has an even [bigger dep tree](https://npmgraph.js.org/?q=bunchee) than `pkgroll` (and also is rollup-based)

Then there is [`unbuild`](https://www.npmjs.com/package/unbuild) which I like so much I even did a [conference talk](https://www.youtube.com/watch?v=fpTa6oZR0ms&t=286s) about using it, but it has the [biggest dep tree of all](https://npmgraph.js.org/?q=unbuild) (why load [`cssnano`](https://npmgraph.js.org/?q=cssnano@7.0.3) for just bundling a simple node lib 😭). It's the most extensible of all the options (with escape hatches to run custom rollup plugins), so it's great for more complicated monorepos like I [deal with at my day job](https://github.com/codecov/codecov-javascript-bundler-plugins/).

**Comment by 43081j** [comment]
makes sense

i think lets keep this on tshy for now with the ultimate aim of just moving to esm-only (can't really until eslint can load esm plugins)

unbuild is more than we need here but @pi0 and @danielroe seem pretty interested in the e18e stuff, so im sure they'd be open to suggestions for making it lighter 👀

**Comment by pi0** [comment]
Thanks for feedback and kind words dear @AbhiPrasad. Let's track it upstream: https://github.com/unjs/unbuild/issues/405
